### ISSUE TITLE
Titanium module

### ISSUE THREAD

**Issue by sindresorhus** [torinnguyen/PepperUIDemoFree#1]
This library looks very useful, unfortunately I don't know Obejctive-C, but use JavaScript and [Titanium](http://www.appcelerator.com).

I think there would be a good market for this in the [Titanium Marketplace](https://marketplace.appcelerator.com/home) if you created a [wrapper module](https://wiki.appcelerator.org/display/guides/iOS+Module+Development+Guide). Just a thought.

**Comment by torinnguyen** [comment]
Sorry, I don't have much experience with Titanium, but I definitely know Titanium is not suitable for this kind of high performance UI. This I the reason I stay clear of Titanium.

My component is running at the top of iPad1 capability, any extra layers in between or on top will not make it.
