### ISSUE TITLE
Book Cover fade out when opening book.

### ISSUE THREAD

**Issue by andre-r-gomes** [torinnguyen/PepperUIDemoFree#3]
How do i disable that functionality.

I want the effect of the book opening without it being faded out during the animation? 

Some direction would be great. 

Thanks

**Comment by torinnguyen** [comment]
Hi Andre,

I don't really get what you want to do.

Anyway, ALL book covers are destroyed after the opening animation to save
memory, and recreate when the book is about to close.
It would be quite difficult to change this behaviour.
